### ISSUE TITLE
treasure-map issues

### ISSUE THREAD

**Issue by LevM-A** [pl3xgaming/Purpur#1059]
### Spark link

There is no need because it's crash when you open a chest with treasure map ( but for performance i will paste it)
https://spark.lucko.me/jyRiUj0op1

### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://pastebin.com/5d7m57eA

### Actions to reproduce (if known)

1. 
find a sunken ship somewhere as far from chest, and click on the chest with a treasure map.
![image](https://user-images.githubusercontent.com/59459622/179475309-60afcf96-a6a4-4890-a009-b85e3e5f7689.png)

2. 
your server freezes for a couple of seconds, and if you're lucky, it crashes.

### Purpur version

Current: git-Purpur-1716 (MC: 1.19)*
Previous: git-Purpur-1701 (MC: 1.19)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

1. Using these plugins:
[10:24:55 INFO]: Plugins (25): AdvancedBan, BalancedElytra, BlueMap, Chatty, Chunky, CoreProtect, CoreProtectTNT, GSit, Hat, InventoryRollbackPlus, LightChatBubbles*, LuckPerms, Maintenance, MentionMe*, MiniMOTD, OpenInv, PlaceholderAPI, ProtocolLib, rBookOnline, rHideTags*, rRPChat, SkinsRestorer, spark, TAB, TheTour

2. There are no Datapacks!!!
3. The map is vanilla generated.

**Comment by BillyGalbreath** [comment]
Treasure maps are known to cause lag. This is because they have to load every chunk in an unlimited radius until they find a treasure.

Same goes for things like the `/locate` command, cartographers, dolphins, and possibly other things I am forgetting about.

Paper and Purpur have added options to disable a few of these things. Other than this, there is nothing we can do about it.

https://docs.papermc.io/paper/reference/world-configuration#treasure-maps
https://purpurmc.org/docs/Configuration/#disable-treasure-searching

More information can be found on Paper's issue tracker

https://github.com/PaperMC/Paper/issues/8089
https://github.com/PaperMC/Paper/issues/7963
https://github.com/PaperMC/Paper/issues/7945
https://github.com/PaperMC/Paper/issues/7664
https://github.com/PaperMC/Paper/issues/7660
https://github.com/PaperMC/Paper/issues/7269
https://github.com/PaperMC/Paper/issues/4356
https://github.com/PaperMC/Paper/issues/4349
https://github.com/PaperMC/Paper/issues/4289
https://github.com/PaperMC/Paper/issues/4258
https://github.com/PaperMC/Paper/issues/4228
https://github.com/PaperMC/Paper/issues/4191
https://github.com/PaperMC/Paper/issues/4118
https://github.com/PaperMC/Paper/issues/4110
https://github.com/PaperMC/Paper/issues/4086
https://github.com/PaperMC/Paper/issues/4038
https://github.com/PaperMC/Paper/issues/4019
https://github.com/PaperMC/Paper/issues/3993
https://github.com/PaperMC/Paper/issues/3619
https://github.com/PaperMC/Paper/issues/3614
https://github.com/PaperMC/Paper/issues/3536
https://github.com/PaperMC/Paper/issues/2955
https://github.com/PaperMC/Paper/issues/2950
https://github.com/PaperMC/Paper/issues/2896
https://github.com/PaperMC/Paper/issues/2792
https://github.com/PaperMC/Paper/issues/2781
https://github.com/PaperMC/Paper/issues/2668
https://github.com/PaperMC/Paper/issues/2312
https://github.com/PaperMC/Paper/issues/2191
https://github.com/PaperMC/Paper/issues/1810
