### ISSUE TITLE
Feature Request: Per-player no tick view distance

### ISSUE THREAD

**Issue by Titaniumtown** [pl3xgaming/Purpur#121]
Could the no tick view distance be determined by a permission or a command per-player? I've really wanted this feature for a while and was wondering if anyone thinks that is a good idea.

**Comment by katekerllenevich** [comment]
So Paper already has this through the api, but when used they throw a NotImplementedException (https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0345-Per-Player-View-Distance-API-placeholders.patch)

It says:
`Per-Player View Distance APIs need further understanding to properly implement (There are per world view distances though!)`

Im assuming that Paper couldn't get this to work like they wanted it to. Maybe it could be done here? Maybe not. Just some thoughts.

**Comment by BillyGalbreath** [comment]
Paper used to have per-player view distance patch, which is where that API comes from. However, when Mojang changed up the chunk system in 1.14 the patch was removed because it was no longer compatible.

https://github.com/PaperMC/Paper/blob/master/removed/1.14/0032-Add-player-view-distance-API.patch

The original plan was to eventually figure out the new chunk system and add it back

https://github.com/PaperMC/Paper/issues/2098

Which Leaf tried to do, and even had a working implementation in Tuinity that was being tested before pushing it to Paper

https://github.com/Spottedleaf/Tuinity/commit/03bb74ee10c6decbcbcca41a99abe52aa34c60d6

However, plugins already started adapting to not having the feature anymore and throwing it back in caused many of them to break, including Citizens.

https://github.com/Spottedleaf/Tuinity/issues/40

So the patch was again reverted, and there currently are no plans to bring it back that I am aware of. It's simply an unmaintainable API these days

https://github.com/Spottedleaf/Tuinity/issues/103

There is one plugin that's been trying hard to maintain such a thing, but it runs into the same issues with other plugins like Citizens.

https://www.mc-market.org/resources/13692/

If this API was to come back in a server implementation it would be in Paper. I'd recommend opening a ticker with them to see where they stand on it, because it's simply too big of a task for me or leaf to maintain and keep bug free
