### ISSUE TITLE
[Feature Request] Support the latest world generation and dimension features.

### ISSUE THREAD

**Issue by datsanakas** [pl3xgaming/Purpur#124]
With the reintroduction of customised world generation in 1.16, datapacks can now be created to leverage these functionalities. Packs that modify the generation features in current existing worlds work just fine, however packs that add new dimensions with custom namespaces are broken on bukkit and its derivatives. I expect this is because worlds and dimensions are stored differently from vanilla? It would be great if we could use these packs in conjunction with the plethora of features Purpur offers, instead of relying on the vanilla server.

**Comment by BillyGalbreath** [comment]
This is something that would have to be implemented in CB itself, as the feature you want st broken by CB because of how it loads worlds. Changing it downstream would break compatibility with plugins.

Here's the open ticket for CB to implement this:

https://hub.spigotmc.org/jira/browse/SPIGOT-6073
