### ISSUE TITLE
Anvil item names and formatting is buggy

### ISSUE THREAD

**Issue by xGinko** [pl3xgaming/Purpur#1252]
### Spark link

https://spark.lucko.me/FRacraa6TO

### Expected behavior

Using the permissions:

```
purpur.anvil.color
purpur.anvil.format
purpur.anvil.remove_italics
```

and setting `anvil.allow-colors: true` should allow a player to use all color and format codes (&k,&m,&l,&6,etc.) available
inside the anvil.

### Observed/Actual behavior

All color and format codes work, except for the &k-format code. Itemnames will just say &kExample

### Steps/models to reproduce

- get luckperms + purpur
- enable config section  `anvil.allow-colors: true` in purpur.yml
- restart server
- give yourself the permissions: 
```
purpur.anvil.color
purpur.anvil.format
purpur.anvil.remove_italics
```
- Try renaming an item to &kEpic Sword

### Purpur version

Current: git-Purpur-1895 (MC: 1.19.3)
Previous: git-Purpur-1883 (MC: 1.19.3)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Minimessage-format in anvils will work when enabled, BUT:
When having both permissions - `purpur.anvil.minimessage` and `purpur.anvil.color+purpur.anvil.format`, only minimessage will work in the anvil. Color and Format codes using the '&' prefix will not work, but instead the color code will be removed from the name.

**Comment by granny** [comment]
> Minimessage-format in anvils will work when enabled, BUT:
When having both permissions - `purpur.anvil.minimessage` and `purpur.anvil.color+purpur.anvil.format`, only minimessage will work in the anvil. Color and Format codes using the '&' prefix will not work, but instead the color code will be removed from the name.

Intentional behavior. If the `blocks.anvil.use-mini-message` option is enabled and the player has the `purpur.anvil.minimessage` permission, then color codes will be stripped in favor of using the MiniMessage tags. Color/format codes cannot be used interchangeably with MiniMessage tags.

**Comment by xGinko** [comment]
@granny can you please read the rest of the issue before closing? You only addressed one thing out of 2.

**Comment by xGinko** [comment]
Ah I see its been addressed in https://github.com/PurpurMC/Purpur/commit/7a5b6a53f12bc547a3afb0b6b39c7193b3d059be

Thank you for your time! :)
