### ISSUE TITLE
Feature request: make more enchantments stackable

### ISSUE THREAD

**Issue by kevindwitama** [pl3xgaming/Purpur#128]
There's already an option to allow mending and infinity to go together, might as well go all the way and add all the other 'illegal' but functional enchantment combinations including:

Frost Walker + Depth Strider
Multishot + Piercing
All the protection enchants (which were stackable in 1.14 but then reverted again in 14.3)
All the sword damage enchants (sharpness, bane, smite)

The only illegal combinations which actually conflict are Silk touch + Fortune and Riptide + Loyalty/Channeling

More info on the Minecraft wiki: https://minecraft.gamepedia.com/Enchanting#Summary_of_enchantments_by_item

**Comment by datsanakas** [comment]
Configurable maximum enchantment levels from tables, anvils, etc, would be cool too.

**Comment by BillyGalbreath** [comment]
Unfortunately, many (if not all) of the compatibility restrictions on the enchantments are there for a reason. They either imbalance the gameplay, create over powered situations, break altogether, etc. We opted to add the option for mending+infinity even though it does create an over powered situation because that was a long standing feature of the game for years, only recently made incompatible. The option was added for nostalgia reasons.


> Configurable maximum enchantment levels from tables, anvils, etc, would be cool too.

We did [have this](https://github.com/pl3xgaming/Purpur/blob/ver/1.15/patches/server/0103-Configurable-enchantment-max-level.patch) for a short while. It was found to break most enchantments, though, so was removed.

**Comment by kevindwitama** [comment]
> Unfortunately, many (if not all) of the compatibility restrictions on the enchantments are there for a reason. They either imbalance the gameplay, create over powered situations, break altogether, etc.

I agree that having some enchantments stackable, especially the protection and damage enchants, can be overpowered, but to be fair Purpur does add some features that affects game balance in a different way, such as increased chest slots, ridable mobs, etc. I just think its nice to have options.

Regarding being broken altogether, the combinations I've listed seem to work fine according to the minecraft wiki, but there may be some other problems that I don't know about, in which case I understand if it is indeed unfeasible.
