### ISSUE TITLE
Infinite lava source

### ISSUE THREAD

**Issue by sintaxcz** [pl3xgaming/Purpur#1284]
### Spark link

no

### Expected behavior

Infine lava source like water

### Observed/Actual behavior

when set to true in config nothing happens still behave like vanilla

### Steps/models to reproduce

set infinite lava source to true in config

### Purpur version

1927 (MC:1.19.3)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
This is intended behavior. That option was actually supposed to be removed since the introduction of the `lavaSourceConversion` and `waterSourceConversion` gamerules from the 1.19.3 update. The config option still existed, just unused. Not sure why it wasn't removed when we updated to 1.19.3 :man_shrugging: Use the gamerules I mentioned instead.
