### ISSUE TITLE
MonsterEggSpawnEvent never fires

### ISSUE THREAD

**Issue by Aztlon** [pl3xgaming/Purpur#1309]
### Spark link

N/A

### Expected behavior

MonsterEggSpawnEvent firing when a mob is spawned from a spawn egg

### Observed/Actual behavior

The event is not fired at all

### Steps/models to reproduce

ummm

### Purpur version

Any version after Purpur 1.19.3

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

### Other

You can read about this on the Purpur Discord; the conversation begins with this message https://discord.com/channels/685683385313919172/720374890472931328/1096161582435794965

**Comment by granny** [comment]
The `MonsterEggSpawnEvent` was removed during the update to 1.19.3 because of the heavy maintenance burden from all the changes to the `EntityType` class.

I'll be keeping this issue open until I've taken a look into adding it back.

**Comment by KioProject123** [comment]
I'm not sure if it's appropriate to explain here, please forgive me if I offend.

If some functionality is removed in the future, can developers be reminded in a more obvious way, such as marking the API as deprecated, or something like that.

For example a developer may use a MonsterEggSpawnEvent to prevent certain players from spawning mobs in a protected area, but may not find out that this functionality is broken until a problem occurs.

This will cause some developers not to dare to use the API provided by purpur, but to choose the upstream API, because they do not know when it will become invalid, and there is no explanation anywhere.
(translated using translation software)

**Comment by BillyGalbreath** [comment]
> I'm not sure if it's appropriate to explain here, please forgive me if I offend.
> 
> If some functionality is removed in the future, can developers be reminded in a more obvious way, such as marking the API as deprecated, or something like that.
> 
> For example a developer may use a MonsterEggSpawnEvent to prevent certain players from spawning mobs in a protected area, but may not find out that this functionality is broken until a problem occurs.
> 
> This will cause some developers not to dare to use the API provided by purpur, but to choose the upstream API, because they do not know when it will become invalid, and there is no explanation anywhere. (translated using translation software)

That's my bad. I was supposed to remove the entire event when I removed it's implementation. Sadly, because of the order things happen during an update, I forgot to go back to the API to remove it.

Here's my train of thought of just flat out removing it. If a developer doesn't notice the entire event is missing, then they wouldn't notice a deprecation warning... ;)

**Comment by granny** [comment]
I've gone ahead and removed the event from the API starting with 1.20 (even though it hasn't done anything since we updated to 1.19.3). The maintenance burden outweighs the benefits of the event. (and it doesn't seem like that many people will miss it...)
