### ISSUE TITLE
ERROR Could not pass event PlayerBedEnterEvent to CMI v9.5.0.9

### ISSUE THREAD

**Issue by danyadanya2005** [pl3xgaming/Purpur#1325]
### Spark link

https://spark.lucko.me/xNXqsk2nwt

### Expected behavior

Please correct the error. I was sent to you

### Observed/Actual behavior

https://pastebin.com/gqXyseq7

### Steps/models to reproduce

I still don't understand what causes the error but it definitely happens when the player goes to bed
https://github.com/Zrips/CMI/issues/7831

### Purpur version

Current: git-Purpur-1967 (MC: 1.19.4)*
Previous: git-Purpur-1833 (MC: 1.19.2)
* You are 5 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
This is not a Purpur issue. This is a CMILib issue with incorrect casting.

https://github.com/Zrips/CMILib/blob/main/src/main/java/net/Zrips/CMILib/Reflections.java#LL1817C32-L1817C32

Here they are getting `aH()` which is a `LootTableRegistry` not a `LootPredicateManager`.

![image](https://github.com/PurpurMC/Purpur/assets/332527/2d208268-e132-4060-a62c-c58484fe0437)

![image](https://github.com/PurpurMC/Purpur/assets/332527/63797669-8688-43ae-bfa8-8e0025cff2fe)

If you would have done what the CMI people suggested and tried this on Paper instead of coming to Purpur, you would have realized this error also happens on Paper servers because it is a bug in the CMILib plugin.

The actual method they want (instead of `aH()`) is the `aI()` method.

![image](https://github.com/PurpurMC/Purpur/assets/332527/9c0073a3-bd9b-4a51-a234-f52df7bd0914)

![image](https://github.com/PurpurMC/Purpur/assets/332527/25d81209-42fd-4509-9e51-91cfbe77fba8)

The reason they are _not_ using the `aI()` method is because you're running a server with NMS version `v1_19_R3` which is _not_ equal or lower than CMI's expected value of `v1_19_R1`
