### ISSUE TITLE
Console colors are not available [≥1.20.1 - 2020]

### ISSUE THREAD

**Issue by shuiqing2046** [pl3xgaming/Purpur#1402]
### Spark link

null

### Expected behavior

null

### Observed/Actual behavior

≥ purpur-1.20.1-2020  console colors are not available

1.20.1-2019
![IMG 20230730024417](https://github.com/PurpurMC/Purpur/assets/28628358/741fcd22-c46e-4577-8a4e-e5acc74393e2)

1.20.1-2020 ~2022
![IMG 20230730024620](https://github.com/PurpurMC/Purpur/assets/28628358/15f1a5ea-4439-4589-a60e-0d3b30e02d10)

### Steps/models to reproduce

null

### Purpur version

Console color available version:  ≤1.20.1-2019

Console color unavailable version: ≥1.20.1-2020

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
1. > - [X]  I ticked all the boxes without actually reading them
2. spark link is required for a reason
3. this is an upstream issue, but i've pushed a hotfix for purpur in the mean time while we wait for a proper fix from upstream https://github.com/PurpurMC/Purpur/commit/41b121b718222d9aa06738ba488a1307deb8c4d0

**Comment by Huge-mistake** [comment]
https://github.com/KyoriPowered/ansi/pull/29
https://github.com/PaperMC/Paper/pull/9546
Shouldn't this be a mistake, it's intentional?

**Comment by BillyGalbreath** [comment]
I agree, it is a mistake for Paper to be making those kind of assumptions based on a flimsy environmental variable that has proven for over 30 years to be unreliable for determining color support. At least they could have assumed the opposite where most terminals in 2023 can and do support the full range of 24bit colors, not 16 or none.

For those that want their true 24bit colors back and happen to be using one of terminal softwares that do not set the environmental variable the way paper team is assuming it should be, you can simply add the `net.kyori.ansi.colorLevel` system property flag to your startup script. For example:

```
java -Dnet.kyori.ansi.colorLevel=truecolor -jar purpur.jar nogui
```

`truecolor` will get you the full 24 bit colors. If you're in the 1% of users with a terminal that doesn't support 24bit colors there are also `indexed256` and `indexed16` values to that flag to get you 256 and 16 colors, respectfully, rather than being forced into a `none` value with the recent paper/kyori changes.
