### ISSUE TITLE
Budding Amethyst Silk Touch Not Working

### ISSUE THREAD

**Issue by Strahilchu** [pl3xgaming/Purpur#1420]
### Spark link

na

### Expected behavior

For budding amethyst to be silk touched

### Observed/Actual behavior

Setting the config option to true does nothing, budding amethyst breaks anyway

### Steps/models to reproduce

Place budding amethyst and attempt to collect it with silk touch

### Purpur version

na

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by granny** [comment]
> Spark link
> 
> na

> Purpur version
> 
> na

You did not fill out the template correctly. Please do not submit issues incomplete. I am now forced to make a bunch of assumptions in regards to your issue.

That config option was removed on newer versions of Purpur since it's something that can be done through a datapack, which is [available here](https://modrinth.com/datapack/purpurpacks-silk-touch-budding-amethyst) by us.

Normally datapacks tend to cause a lot of lag to your world through the use of functions. Since this feature is data-driven, it will not cause you any lag from using it.
