### ISSUE TITLE
Zombie and Skeleton Horses Do Not Respect WorldGuard Deny-Spawn Flag on Purpur

### ISSUE THREAD

**Issue by maeeeeee** [pl3xgaming/Purpur#1458]
### Spark link

https://spark.lucko.me/txVJNFUufp

### Expected behavior

Zombie and skeleton horses should respect the deny-spawn flag when added to a WorldGuard region. Tested by using Paper 1.20.2 build 291 and Purpur 2090, and the issue only appears on Purpur. EngineHub told me the solution was to switch to Paper, which I'd ideally rather not do, hence making an issue here.

### Observed/Actual behavior

Zombie and skeleton horses are able to spawn regardless of WorldGuard region deny-spawn values.

### Steps/models to reproduce

1. Set zombie_horse and/or skeleton_horse in a region's deny-spawn flags
2. Attempt to spawn zombie/skeleton horse via spawn eggs or whatever other method
3.
![image](https://github.com/PurpurMC/Purpur/assets/52181624/09a77970-85f1-4c88-b9e3-9c3e417b1b33)

### Purpur version

Current: git-Purpur-2090 (MC: 1.20.2)*
Console 21:05:53
Previous: git-Purpur-2088 (MC: 1.20.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Purpur.

**Comment by Krakenied** [comment]
https://github.com/PurpurMC/Purpur/blob/ver/1.20.2/patches/server/0025-Zombie-horse-naturally-spawn.patch#L15-L24
Purpur doesn't change anything except that, but there is nothing that would cause the described issue

**Comment by Krakenied** [comment]
How about Pufferfish?

**Comment by Krakenied** [comment]
ok, can confirm on Purpur but not on Paper and Pufferfish

**Comment by Krakenied** [comment]
it's broken even on Purpur 1.16.5

**Comment by granny** [comment]
[In Worldguard](https://github.com/EngineHub/WorldGuard/blob/4a501a49db5a780fbf2b8e57a4cb9d54e8e2d0be/src/main/java/com/sk89q/worldguard/bukkit/WorldGuardEntityListener.java#L767-L771) they have a check for tamed mobs right before that flag goes into effect. In purpur, almost since the creation of the project, zombie and skeleton horses would default to always being tamed. This should remedy that by only showing those two mobs as tamable if they're tamed (like it should) OR if the new ridable options are enabled.

**Comment by xGinko** [comment]
I just saw this while updating and the picture caught off guard lmao
