### ISSUE TITLE
Option to hide "Unable to resolve BlockEntity for ItemStack" messages.

### ISSUE THREAD

**Issue by mibby** [pl3xgaming/Purpur#15]
Would it possible to add an option to hide Unable to resolve BlockEntity for ItemStack messages in console? I seem to get these two messages quite frequently in my logs, unsure if it's caused by newly spawning hives/nests from 1.15.2 gameplay mechanic or the old Purpur patch that made them spawn in.

```
[12:36:25] [Craft Scheduler Thread - 1305/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:beehive
[12:36:25] [Craft Scheduler Thread - 1305/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:beehive
```
```
[12:37:55] [Craft Scheduler Thread - 1232/WARN]: Unable to resolve BlockEntity for ItemStack: minecraft:bee_nest
```

**Comment by BillyGalbreath** [comment]
This warning is part of DFU on itemstacks and happens when it cant find an entity id in the BlockEntityTag. This means, you have a misbehaving or misconfigured plugin trying to create ItemStacks with invalid entity id's in the BlockEntityTag. Most likely an outdated SilkSpawner type plugin (just a guess).

Closing as "plugin fault". Will reopen if you can provide reproduction steps with no plugins.

**Comment by mibby** [comment]
Is there an easy way to debug where the BlockEntity message is coming from? Unfortunately I don't use SilkSpawners or any similar type of plugin and the plugins that may modify stuff bee related (pets/disguises) don't seem to throw out the error when I tested.
