### ISSUE TITLE
(Suggestion) Add configurable banner layer stack limit

### ISSUE THREAD

**Issue by LichLord91** [pl3xgaming/Purpur#154]
Would like to see a way to set the amount of banner layers you can stack. The current hard limit is 6 unless in creative mode, using a command block, or generator command like /give .  

Be nice if we can set that limit (which i think you can do 16 max?) so that all players can do it without a workaround.

**Comment by jensenrob91** [comment]
Seems shields attached with banners that have more than 6 layers do not show the additional layers as well, not sure if thats something that can be adjusted as well but that'd be great.

**Comment by BillyGalbreath** [comment]
I'm not sure how possible this is, but will definitely look into it soon(tm) Would be neat to have

**Comment by LichLord91** [comment]
I believe , through my googling's not personal experience, that there's some plugins out there that have done this. If it'd help I'd be happy to find some and test it out/link it too you. Thanks for taking a gander at all Billy <3

**Comment by BillyGalbreath** [comment]
Can you show me one of these plugins? I've checked the code, and unfortunately the loom is mostly client side controlled. I cannot make the center pattern section of the loom enable from the server side if there are already 6+ patterns on the banner.

![image](https://user-images.githubusercontent.com/332527/107863494-6d7c4d80-6e1a-11eb-98dc-a3d3c05784a9.png)

**Comment by LichLord91** [comment]
Hey billy this was the only one i could find that seems to add this functionalitly through the loom all others seem to do it through a custom GUI or such. At least that i can find. This plugin is form 1.13 though , hopefully you'll find something useful.

https://www.spigotmc.org/resources/betterbanner-1-13.63993/

https://github.com/sarhatabaot/BetterBanner

**Comment by BillyGalbreath** [comment]
Yeah, that plugin uses the old pre-1.14 system before Looms were a thing. It uses the old recipe system. Looms replaced that old recipe system since recipes are now server side data driven. This change was very important because with 16 blank banners, 38 patterns of 16 colors each (608 uniquely-colored patterns), and 0 to 6 patterns per banner, players can create approximately 809 quadrillion uniquely crafted banners. Each one would be it's own recipe.. So that system is out of the question.

Unless there is a way for the server to tell the client to enable the center pattern in the Loom gui, this is simply impossible. :(

**Comment by LichLord91** [comment]
This makes me a sad panda. :( Thanks Billy for taking a look into this and the detailed explanation , i love learning about this stuff. I'm relatively new to the Minecraft scene, started in beta but didn't pick it back up until last few months. Learning a lot thanks for always being so helpful. <3
