### ISSUE TITLE
PvP Systems

### ISSUE THREAD

**Issue by Arvesa** [pl3xgaming/Purpur#162]
Make a PvP system to change:

- [ ] Knockback value
- [ ] Hit delay
- [ ] Hit cooldown
- [ ] Fishing rod hook speed and damage
- [ ] Burn damage and delay
- [ ] Item damages
- [ ] Potion effects
- [x] Offsets and speeds for
  - Arrows
  - Splash potions
  - Lingering potions
  - Bottle o' enchanting
  - Snowballs
  - Eggs
  - Ender pearls
  - Ender eyes
  - Fire charges

**Comment by YouHaveTrouble** [comment]
I can see how projectile offsets and speed could be useful.
The first part though, knockback and hit delay, you can easily manipulate using plugins.

**Comment by BillyGalbreath** [comment]
Wow. This is a mouthful of features in one sentence :3 Will look into them in time

**Comment by danechek** [comment]
> I can see how projectile offsets and speed could be useful.
> The first part though, knockback and hit delay, you can easily manipulate using plugins.

Why plugins if you could do it without them?  Good settings, still knockback/hit delay should be configured separately for each weapon

**Comment by danechek** [comment]
It would also be nice if hit delay could be configured in two variations - for hit to a player in armor and for without armor. Likewise, a separate configuration for hit delay after hitting a player with a shield, that is, so that there is some breath after hitting a player who is blocking the blow with a shield. For a player with a shield, there is already a cooldown in the paper, so we need to do a “reverse cooldown”.

**Comment by MWHunter** [comment]
Fishing rood hook speed can be reverted back to 1.8 with OldCombatMechanics: https://github.com/kernitus/BukkitOldCombatMechanics/blob/master/src/main/java/kernitus/plugin/OldCombatMechanics/module/ModuleFishingRodVelocity.java


1.8 knockback levels with https://github.com/MWHunter/KohiKB/blob/master/src/main/java/org/abyssmc/kohikb/KohiKB.java


Disabling netherite knockback resistance would be nice because it is very difficult to do that with a plugin.

**Comment by YouHaveTrouble** [comment]
> Disabling netherite knockback resistance would be nice because it is very difficult to do that with a plugin.

It's not. People are just going roundabout way about it. You just need to remove the knockback resistance from the armor in the recipe and scan player armor on hit to remove the stat.

**Comment by MWHunter** [comment]
> > Disabling netherite knockback resistance would be nice because it is very difficult to do that with a plugin.
> 
> It's not. People are just going roundabout way about it. You just need to remove the knockback resistance from the armor in the recipe and scan player armor on hit to remove the stat.

And then you have a bunch of netherite armor that has no knockback resistance after you uninstall the plugin.  Potentially fine for a private plugin, but all public plugins should be able to be uninstalled completely.

**Comment by BomBardyGamer** [comment]
If this is so people can add awful 1.8 PvP mechanics into the latest version then I downvote this. Otherwise, looks like a great idea!

**Comment by Cypphi** [comment]
> If this is so people can add awful 1.8 PvP mechanics into the latest version then I downvote this. Otherwise, looks like a great idea!

I think this is great. Sword pvp with full netherite is literally endless. If you were to remove the delay so people can spamclick you'd deal much more damage making fights not last 30 minutes. (or you use end crystals like me xD)

**Comment by YouHaveTrouble** [comment]
> I think this is great. Sword pvp with full netherite is literally endless. If you were to remove the delay so people can spamclick you'd deal much more damage making fights not last 30 minutes. (or you use end crystals like me xD)

That's because you don't use swords in the new pvp, you use axes and shields, because they're more effective, and frankly, way more fun.

**Comment by BillyGalbreath** [comment]
I'm gonna go ahead and close this. It is indeed apparent now that this is aimed at bringing back 1.8 combat style. There's an existing plugin for that already, OldCombatMechanics. ;)
