### ISSUE TITLE
(Suggestion) Add stack mob

### ISSUE THREAD

**Issue by Misio12320** [pl3xgaming/Purpur#174]
Hii. Could you might add a stackmob option like plugin StackMob? The plugin contains useless commands for my server and I don't want to break my product server while testing their commands.
Should be a config to stack entities true/false. Change color of stacked mobs, type etc.

**Comment by BillyGalbreath** [comment]
No.

**Comment by YouHaveTrouble** [comment]
I feel like a little bit more explanation would be nice, so here I go! 
Stacking mobs is not a good idea generally speaking. When you stack naturally spawned mobs server will constantly try to spawn more mobs in, because it sees stacked mobs as one mob. Purpur doesn't add features that are blatant hit on the performance. That's most likely why this was denied.
