### ISSUE TITLE
(Suggestions) Very compact source of suggestions

### ISSUE THREAD

**Issue by craftish37** [pl3xgaming/Purpur#180]
Hey, I was thinking about cool functionalities:

**1. make a stats system for all the ridable mobs like the horses stats**
As you know, horses have speed and jump stats, I think it can be really cool to search and breed mobs for making the best mount ever

**2. bow enchants on the crossbow and the opposite**
Put infinity, punch, power and flame on a crossbow and works like a bow
Put piercing, multishot and quick charge on a bow and works like a crossbow

**3. make fireballs (item) launchable like ghasts by right-clicking**
by right click with a fireball (item) it summon a ghast fireball who go in the direction you are looking

**4. make lava spongeable**
Like water, make lava drainable with sponges ;-;

**5. does armor stand spawns with arms/base & other**
add the possibility to have arms and no base (configurable) when you place an armor stand in survival, it can be useful for decoration and using no commands

**6. walls and iron bars can be a leash support**
PLS 😭

**7. configurable piston stickable/pushable blocks**
add the possibility to push and pull blocks like obsidian

**8. if respawn anchor needs glowstone to work**
Use the respawn anchor "like" a bed so don't use glowstone every time you die to reload it

**9. _maybe the max stack size of items_**
MEGA STACKZ GO BRRR

**10. control if lightning bolts can or not transform villager in witch**
Control if villagers can be transformed in witch when strucked by lightning bolt

**11. if the channeling enchant needs to touch an entity to summon a lightning bolt**
I need this, Zeus told me to purify this world by using fire, so I do it

**12. if brewing stand needs blaze powder to work**
idk why mojang have add this, potions are already expensive O_o

**13. make a special action with the sheep who makes it colorful (like the Jeb_ easter egg)**
sheep-o-disco guys !!!🕺

**14. configure the special attack of the phantom with different particles**
Phantoms are cool, phantoms who throw fire too, but what about phantoms who throw blue fire or toxines ? 🤔

~~**15. configure the snowball damage**~~
~~snowballs are bullets, snow golems are ghatelins~~
[Already possible](https://pl3xgaming.github.io/PurpurDocs/Configuration/#projectile-damage)

**16. can plant warts on soul soil**
soul sand is cool, but walk at 3km/h in plants not

**17. create expand mob spawning like zombies with different pieces of armor, enchant or not etc...**
it can be really cool to have new kind of zombie army, they are too weak for my power now ᕦ(ò_óˇ)ᕤ

**18. maybe an auto riptide trident without enchant it**
Trident is a good weapon, how many of us have lost a non-riptide trident by launch it on a cow on the mountain ?

**19. and all the ideas I can find later**

I've tried to be the more clear as possible, but if you have questions about theses suggestions, ask me :p
P.S.: please note I'm french 🙆‍♂️

**Comment by YouHaveTrouble** [comment]
1 seems like an absolute nightmare if you want to use anticheat.
I'm pretty sure 15 is already implemented.
Also pretty positive 13 is client side, so pretty much impossible without renaming the sheep.

**Comment by BillyGalbreath** [comment]
1. `make a stats system for all the ridable mobs like the horses stats`
i am working on exposing all entity attributes to the config. but i wont go as far as making a breeding system like horses. not worth the time/effort. someone that wants to dedicate their time to this single thing could make a plugin to handle such a thing easily.

2. `bow enchants on the crossbow and the opposite`
thats not how this works. how are you going to quick charge a bow when a bow cant be charged? some things can be done, but are best left up to a plugin. i made a small private plugin for my server, for example, that lets players shoot an entire stack of arrows with a single shot.

3. `make fireballs (item) launchable like ghasts by right-clicking`
there is no fireball item. i think you mean the fire charge, which doesnt make sense. this is best suited for a plugin for anyone thats wants such an odd feature.

4. `make lava spongeable`
an even odder request, that wouldnt make much sense. a soaked sponge is full of water, not lava, and that cannot be changed without a client side mod.

5. `does armor stand spawns with arms/base & other`
i thought about this a few times, but came to the conclusion this is best left to a plugin. there are plenty of plugins out there that already do it and a lot more.

6. `walls and iron bars can be a leash support`
not possible without a client side mod

7. `configurable piston stickable/pushable blocks`
this is very doable, but very limited. purpur already offers the option to allot slime blocks to be configured for this. but thats because slime blocks are the root of most dupe/lag machines. i dont think i will be making each and every block configurable for this.

8. `if respawn anchor needs glowstone to work`
easily achievable with a small 5 line plugin.

9. `maybe the max stack size of items`
not really possible. too many areas of the server _and_ client are hardcoded. there are plenty of plugins that try to overcome this limitation and make them configurable, but all end up having issues one way or another.

10. `control if lightning bolts can or not transform villager in witch`
there is already api exposed for this by bukkit. would take a tiny 5 line plugin.

11. `if the channeling enchant needs to touch an entity to summon a lightning bolt`
easily achievable with a small 5 line plugin

12. `if brewing stand needs blaze powder to work`
i dont agree with this idea. i'm sure a plugin could bypass it if you really wnated.

13. `make a special action with the sheep who makes it colorful (like the Jeb_ easter egg)`
already exists. nametags.

14. `configure the special attack of the phantom with different particles`
phantoms are already the most configurable entity in purpur. i dont think i will be doing anything else with the phantom until i'm finished with other things that are piled on my plate (like making the dragon spit fire when ridden, etc)

15. `configure the snowball damage`
Already possible

16. `can plant warts on soul soil`
[soul speed](https://minecraft.gamepedia.com/Soul_Speed)

17. `create expand mob spawning like zombies with different pieces of armor, enchant or not etc...`
vanilla already does this. put your server in hard mode, then the moon phase will change what armor/enchants mobs get. spiders can even spawn in with invisibility, etc.

18. `maybe an auto riptide trident without enchant it`
fuck tridents. they would be banished if I had my way.

19. `and all the ideas I can find later`
i would highly suggest learning how to make bukkit plugins. a lot of these ideas you had can be banged out in 5 minutes or less with minimal code.
