### ISSUE TITLE
[Feactures] Unlimited max level in Anvil

### ISSUE THREAD

**Issue by DoctaEnkoda** [pl3xgaming/Purpur#25]
Create a Patch who modifie : ContainerAnvil.java 

```
    private final EntityHuman player;
    // CraftBukkit start
    public int maximumRepairCost = Integer.MAX_VALUE; // old is 40 or config set Maxium
    private int lastLevelCost;
```

**Comment by BillyGalbreath** [comment]
I believe Bukkit API already has what you're looking for

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/AnvilInventory.html#setMaximumRepairCost-int-

**Comment by Jikoo** [comment]
This isn't a simple change to one value. Changing maximum repair cost alone doesn't work - unlike most inventory interaction, the client actually will not send packets if it doesn't think it can withdraw the result. It will only send the click for levels over 40 if it is in creative. Additionally, the client uses a short to represent the repair cost, which means numbers over 32767 are not rendered properly under any circumstances, though the server can technically support them.

I wrote [AnvilUnlocker](https://github.com/Jikoo/AnvilUnlocker) as an experiment to see if I could trick the client into sending the packet anyway. Requires ProtocolLib because I have no plans to maintain or develop it further.

**Comment by BillyGalbreath** [comment]
Unfortunately, Jikoo is correct. The client doesn't send any click events to the server if the cost is not 1-39. You'll have to trick the client by setting the window property to 1-39 and use the method from Bukkit API I mentioned before. Not a clean solution, I know :(
