### ISSUE TITLE
Suggestion: zombified piglin portal spawn limiter/controller

### ISSUE THREAD

**Issue by MrEDok** [pl3xgaming/Purpur#279]
**suggestion**
zombified piglin portal spawn limiter/controller
- when player build alot/big gold farm piglin spawning increase alot and cause alot of lag. there option to disable piglin AI but in my case it would be impossible to enable that option so i wonder if it possible.

solution ig
when portal try to spawn a piglin it check how many hostile mob there are in that area and if it over x count in bukkit.yml it wont spawn anymore piglin.

**Comment by BillyGalbreath** [comment]
This is designed to work this way. Spawns like this (and many other areas of the game) do not check the mob limits by design. If you want to modify that there are existing plugins (like farm limiter, etc) that do this.

However, I went ahead and exposed the spawn chance modifier to the config in build 1056 https://github.com/pl3xgaming/Purpur/commit/24d9e61d2e9e395a5172d644965c931b01b0234d its not exactly what you wanted here, but it might help you and would definitely be useful for other things.
