### ISSUE TITLE
Paper Watchdog Thread/ERROR

### ISSUE THREAD

**Issue by koyere** [pl3xgaming/Purpur#291]
**Describe the bug**
Well, suddenly it starts to happen and then throws the server

**To Reproduce**
No

**Screenshots or Videos**
https://paste.gg/p/anonymous/47ad4babcac84680bc2cdbf4a48e1c7d

**Plugins**
 Plugins (69): AdvancedChests, AdvancedEnchantments, AdvancedSpawners, AggressiveAnimals*, AngelChest, antiRedstoneClock, BannerBoard*, BattlePass, BettingGames, BloodNight, BookLimiter, BuycraftX, ChatSentry, Citizens, CMI, CMILib, CoreProtect, DeluxeChat, eco, EpicBackpacks, ExecutableItems, GCore, GCoreLegacy, GriefDefender, GSlotMachine, IllegalStack, InventoryRollback, Iris, KiteBoard*, Lib1711, LibsDisguises, LoneLibs, LuckPerms, MarriageMaster, Masks, MobFarmManager, MoneyHunters, Multiverse-Core, Multiverse-NetherPortals, MyPet, MythicMobs, NexEngine, OreRegenerator, PlaceholderAPI, ProtocolLib, PyroFishingPro, PyroMining, PyroWeatherPro, QuantumShop, QuestCreator, RandomEvents, SpecializedCrates, StratosNG, TAB, Talismans, TrMenu, UChestClan*, UClans, UGladiator, UKing, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGenerator, VoidTeleportPlus, Wind, WorldEdit, WorldGuard

**Version**
Purpur version git-Purpur-1060 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Is bug present on Paper, Spigot, CraftBukkit, or Vanilla**
Be sure you test the upstream projects for this bug and include if it is present or not here, include `/version` output for each upstream project you tested.

**Additional context**
Add any other context about the problem here you think will help resolve the problem.

**Comment by YouHaveTrouble** [comment]
This is 99% a plugin error. Reproduce without plugins.

**Comment by koyere** [comment]
> This is 99% a plugin error. Reproduce without plugins.

That is very general, of course without add-ons it will not affect me, it is obvious, what I need to know is what it could be, I cannot remove them all and try one by one.

Because, because the error occurs when there are players inside, if it is empty nothing happens because it does not load

**Comment by encode42** [comment]
There's not much we can do unless we know your server setup. As the log lines state, "The server has not responded for 10 seconds" which indicates that the server is lagging. This could be caused by inadequate hardware, faulty disk IO, plugins, and more.

The thread dump has multiple references to a plugin named `advancedplugins`. You should start with that.

**Comment by koyere** [comment]
> There's not much we can do unless we know your server setup. As the log lines state, "The server has not responded for 10 seconds" which indicates that the server is lagging. This could be caused by inadequate hardware, faulty disk IO, plugins, and more.
> 
> The thread dump has multiple references to a plugin named `advancedplugins`. You should start with that.

Could it be the generation of custom worlds with Stratos or iris? They are somewhat heavy indeed ...

**Comment by BillyGalbreath** [comment]
This is a plugin issue.

According to your thread dump report, all dumps are caused by a single plugin (or a single util shared by many plugins.

```java
net.advancedplugins.ae.utils.AManager
```

From your server list, most likely suspects are : `AdvancedChests`, `AdvancedEnchantments`, or `AdvancedSpawn`

Scroll through your thread dump report and see for yourself. Every single dump is from this util.

![image](https://user-images.githubusercontent.com/332527/116301373-951a5b00-a765-11eb-8cfb-3cdf3ab76991.png)
