### ISSUE TITLE
MythicMobs error with purpur but not paper

### ISSUE THREAD

**Issue by Castiella** [pl3xgaming/Purpur#3]
https://pastebin.com/na9TiNwM

Mobs spawn with the command, but not with randomspawns.

This plugin works as intended on Paper 1.14, however, using the latest build of 
purpur causes the error. I'm not sure why Purpur could be causing this as it is literally a fork of paper.

Any help would be appreciated.

**Comment by BillyGalbreath** [comment]
Unfortunately, since that is a closed source plugin I am unable to diagnose it on my end. I even tried looking for a girhub link on their free version, to no avail. You'd have to report it to the developers of MythicMobs to see what they say. It looks like a simple case of not knowing what purpur is so it falls back to a bukkit adapter instead of paper adapter.

**Comment by lukeeexd** [comment]
Aw this is a shame, my new server will use MythicMobs and was gona use purpur

**Comment by PhanaticD** [comment]
is this still an issue? I was actually going to use mythicmobs as well but its a big investment not worth it if it doesnt even work

**Comment by BillyGalbreath** [comment]
After discussing it further on Discord and testing it myself I was unable to reproduce this issue.
