### ISSUE TITLE
Naturally spawned piglins still contribute to the mob cap when PersistenceRequired is true

### ISSUE THREAD

**Issue by kADOMPHy** [pl3xgaming/Purpur#325]
**Describe the bug**
This is an duplicate of these issues - [SPIGOT](https://hub.spigotmc.org/jira/browse/SPIGOT-6278), [PAPER](https://github.com/PaperMC/Paper/issues/4635). They doesn't seem to be fixed or will be fixed soon. Maybe it's possible to be fixed in purpur?

**Comment by BillyGalbreath** [comment]
Sure enough, I summoned a bunch of natural piglin and made them all pickup pumpkins to make them persistent (used the commands provided in the linked Paper ticket), then all other spawns in the nether stopped. The mob cap was counting them all :3

The red arrows are pointing to some debug output that counts all the monster type mobs in the nether, then spits out the current mob count in the mob cap
![image](https://user-images.githubusercontent.com/332527/117641483-cf173400-b14b-11eb-99b5-4ed5bcbe1d44.png)

I killed all the other mobs, including non-persistent piglins with this command
```
/kill @e[type=piglin,nbt=!{PersistenceRequired:1b}]
```
![image](https://user-images.githubusercontent.com/332527/117642093-8f048100-b14c-11eb-83da-2f6fe75bcc37.png)

After that, I enabled my fix by returning true in `EntityPiglin#isTypeNotPersistent` and instantly the current mob cap dropped to 1 because there was 1 strider left somewhere that wouldn't kill.. and instantly the server spawned a bunch of mobs until the my configured cap of 70 was hit
![image](https://user-images.githubusercontent.com/332527/117642311-bf4c1f80-b14c-11eb-8b70-bdb650d8b380.png)

None of the piglin were counting towards the mob cap limit that shouldn't have been. Killing off the same entities as before resulting in new spawns immediately happening. \o/
