### ISSUE TITLE
Instant nether portal teleporting works for OPs when it shouldn’t

### ISSUE THREAD

**Issue by DragonBornMage** [pl3xgaming/Purpur#427]
## Expected behavior
Op players should normally go through nether portals

## Observed/Actual behavior
  Ops instantly warp through portals like in creative mode, but in survival.

## Steps/models to reproduce
  Be OP and go through a nether portal, you instantly warp to the other portal

## Purpur version
`VERION GIT-purpur-1204  implementing api version 1.17-R01-SNAPSHOT`

## Agreements
Please agree to the following.
- [ X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [ X] I have searched for and ensured there isn't already an open issue regarding this.
- [ X] My version of Minecraft is supported by Purpur.

## Other

Instant teleporting only happens to OP players 
-->

**Comment by granny** [comment]
Please use the templates instead of cramming everything into the issue title.

**Comment by emielderckx** [comment]
Of course it works for OPs without changing settings. The whole idea is so you don't give people OP, but the perm

**Comment by DragonBornMage** [comment]
Sorry about the template, was on iphone and it isnt great on it. But, regardless, i dont know about most people, but as the OWNER of a server I am OPed and personally i think its something i personally wouldnt want active by default, even as the owner, on myself. Lots of servers have OPs (admins etc) who play the game normally, and I think having it active by default will create unneeded additional questions in the future.

**Comment by emielderckx** [comment]
de-OP your self and then give your self all the perms you need. 
If you need OP use the console or use the console to OP your self for some time and after you're done remove the OP again

**Comment by BillyGalbreath** [comment]
Looking into this more, it seems there is a deeper bug caused somewhere upstream. No one's ever noticed it before because none of the upstreams use the default `false` permission for any built-in commands. All of my [default `false` perms](https://github.com/pl3xgaming/Purpur/blob/ver/1.17/patches/api/0004-Default-permissions.patch) seem to be acting like default `op` perms. I'll have to dig deeper into this.

Temporary solution is to negate the `purpur.portal.instant` permission using your permissions plugin. A better solution would be to not play as Op. Remeber, Op is a tool, not a rank ;)

**Comment by notOM3GA** [comment]
billy they are registered as op somewhere in that patch (different file)

**Comment by BillyGalbreath** [comment]
I have done some more testing, and it is indeed a major bug from upstream. It is even effecting plugins' default permissions.

Monitor this ticket for more information: https://github.com/PaperMC/Paper/issues/6050

**Comment by BillyGalbreath** [comment]
Fixed in build 1221

https://github.com/pl3xgaming/Purpur/commit/617db08a07fec5454b90dbffc222b8a3a1789da2
