### ISSUE TITLE
NMS function name has changed, breaking my plugin

### ISSUE THREAD

**Issue by casperge** [pl3xgaming/Purpur#626]
### Expected behavior

In the class IRegistryCustom (net.minecraft.core) there should be a method:
`public <E> IRegistry<E> d(ResourceKey<? extends IRegistry<? extends E>> key)`
This is the default name of the method: paper, spigot and all other servers use this. 

### Observed/Actual behavior

Since version 1349 this method name has changed, now being:
`public <E> IRegistry<E> registryOrThrow(ResourceKey<? extends IRegistry<? extends E>> key)`
This breaks plugins using custom biomes and would require all devs to make a separate piece of code for purpur-users only. That is definitely not the way to go. All my purpur users are complaining about errors and the plugin not working suddenly after they updated. Reverting back to 1348 would fix it.

### Steps/models to reproduce

Look through the code in net.minecraft.core.IRegistryCustom in the patched jar, you'll see it yourself.

### Purpur version

This server is running Purpur version git-Purpur-1354 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e72be60 on ver/1.17.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpur.pl3x.net/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Sounds like a remapping issue with paperweight. Purpur doesn't touch the registry classes, and we most certainly wound't be renaming methods like that if we did.

@DenWav this might be https://github.com/PaperMC/paperweight/issues/24 or https://github.com/PaperMC/paperweight/issues/45 since we updated to 1.1.11 with build 1349.

**Comment by BillyGalbreath** [comment]
Ok, turns out we [had a workaround before](https://github.com/pl3xgaming/Purpur/commit/ffc533fab34b369a0a53c97767152ae222e5d9ef), but we dropped it when [Tuinity required the same workaround](https://github.com/Tuinity/Tuinity/commit/a4009b4905c536f9b3bafb4f55e2e312be2d9299). Build 1349 we use [Tuinity's merge PR](https://github.com/PaperMC/Paper/pull/6413), which doesnt have that patch anymore because they're now Paper. So I just had to [readd the patch](https://github.com/pl3xgaming/Purpur/commit/3f17a242fa6c1cb5231748d62af56216729087ed) back into Purpur. All is fine now with build 1355+
