### ISSUE TITLE
Crash with EWG

### ISSUE THREAD

**Issue by LukaPix** [pl3xgaming/Purpur#71]
Random very weird Server Crash when genearting an EpicWorldGenerator World.

i first opened it on the EWG Issue tracker but it seems to only happen to purpur.

https://github.com/jonryf/EpicWorldGenerator-bugtracker/issues/126

**Comment by jpenilla** [comment]
Can you test on Tuinity? I would bet this is due to their changes. EWG likely does some sketchy NMS that is broken by Spottedleaf's optimizations.

**Comment by chrismwiggs** [comment]
Can confirm I get the same error on Purpur and Tuinity, but not paper (1.16.2/3).

**Comment by BillyGalbreath** [comment]
The problem is EWG devs dont understand how to properly detect Paper instances. Purpur _is_ a Paper instance, but EWG does not see it as such. Instead, EWG sees Purpur as a generic Bukkit instance.

This is a crucial difference because Bukkit bundles in a java library called FastUtil and they relocate it to a bukkit package. Paper removes the relocation so the package is in the normal place. This means, on Paper and all its forks (Tuinity, Purpur, etc) FastUtil is at its normal location. But EWG errors because it's trying to use FastUtil as Bukkit's relocated location due to EWG's improper Paper detection.

There is nothing I can do to fix this on Purpur's end. It is purely on the plugin side to fix. Good luck, though. EWG devs are notorious for things like this.
