### ISSUE TITLE
[Feature Request] Option to disable riding "neutral" mobs that are between hostile & friendly

### ISSUE THREAD

**Issue by AZFire1** [pl3xgaming/Purpur#73]
**Feature Description:**
I think this feature could possibly be useful if a ridable (neutral) mob (such as polar bear, spider, etc..) is attacking you and you decide you want to make it stop and ride it which stops the mob from doing anything.. I think there should maybe be a way to prevent riding these specific ridable mobs if you are being attacked with a possible config option to toggle this? Not sure if this is really needed though.

**Comment by BillyGalbreath** [comment]
Back in 1.13 days I did try doing something like this when Ridables was a plugin. However, it doesnt work out as well as you'd think. A good example is zombies can target a player from up to 96 blocks away sometimes. This makes zombies pretty much _never_ ridable because they're always targeting a player.

If you have any ideas around this I'm all ears ;)
