### ISSUE TITLE
Configurable Inertia/Acceleration for the Minecart Feature

### ISSUE THREAD

**Issue by Joshinn-io** [pl3xgaming/Purpur#79]
This is a suggestion, not an issue. We're attempting to replicate a Mario kart style racing game, and this Minecart feature is near perfect, so a few suggestions that I'm not sure the feasibility of each one, so feel free to shoot stuff down.

It would be really cool if we could get the boat mechanics of inertia (sliding) and acceleration configurable for when you're riding minecarts.

Another side request (I'm pretty sure this isn't possible due to hitboxes but worth a shot), would it be possible to configure the seating positions on the rideable mobs?

**Comment by BillyGalbreath** [comment]
I'm open to the idea of getting the sliding to work, but it's honestly beyond me. I've tried it before and I can't get it right. PRs are definitely welcome if anyone knows how to do it correctly ^_^

As for the seat height, that's actually client controlled. I had a client mod I was working on for this (PurpurClient), but due to lack of interest and time I have since abandoned it.
