### ISSUE TITLE
PacketPlayOutOpenSignEditor auto close sign

### ISSUE THREAD

**Issue by Lotzyprod** [pl3xgaming/Purpur#806]
### Expected behavior

Opened sign for player

### Observed/Actual behavior

When I open packet sign to player its automatically closes

### Steps/models to reproduce

 purpur
 https://youtu.be/nyWgp1kUVo0
 
 paper
 https://youtu.be/7qET-iJ893w

### Purpur version

This server is running Purpur version git-Purpur-1456 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7551c72 on HEAD)
You are running the latest version
Previous version: git-Paper-68 (MC: 1.18.1)

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Can you provide a simple plugin (source code) so I can replicate this and see what's going on?

**Comment by Lotzyprod** [comment]
> 

Cant provide plugin, because I use Skript. But anyway 
import net.minecraft.network.protocol.game.PacketPlayOutOpenSignEditor;
import net.minecraft.core.BlockPosition;

Location loc = player.getLocation();
((CraftPlayer) player).getHandle().b.a(new PacketPlayOutOpenSignEditor(new BlockPosition(loc.getX(),loc.getY(),loc.getZ())));

**Comment by BillyGalbreath** [comment]
Ok, I wrote a test plugin that simply sends the sign editor packet and have determined this is an upstream issue. Possibly as far up as vanilla. Mojang has been known to change how this stuff works in a negative way in the past (see this ticket where most of my conversation got deleted about it https://bugs.mojang.com/browse/MC-192263).

I have tested my test plugin against Paper build 101 and get the exact same results. I anticipate the same would be seen on CraftBukkit and Spigot, if tried. There isn't anything I can do about this.

Test plugin:

```java
package io.papermc.paperweight.testplugin;

import net.minecraft.core.BlockPos;
import net.minecraft.network.protocol.game.ClientboundOpenSignEditorPacket;
import net.minecraft.server.MCUtil;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer;
import org.bukkit.entity.Player;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

public final class TestPlugin extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (!(sender instanceof Player player)) {
            sender.sendMessage("Player only command!");
            return true;
        }

        BlockPos pos = MCUtil.toBlockPosition(player.getLocation());

        ClientboundOpenSignEditorPacket signEditorPacket = new ClientboundOpenSignEditorPacket(pos);
        ((CraftPlayer) player).getHandle().connection.send(signEditorPacket);

        return true;
    }
}
```

[paperweight-test-plugin-1.0.0-SNAPSHOT.zip](https://github.com/PurpurMC/Purpur/files/7777717/paperweight-test-plugin-1.0.0-SNAPSHOT.zip) (extract this, don't just rename the extension)

In the past, in order to send a fake sign editor window with prefilled text you would first need to send the client a BlockEntityData packet that contained sign text and a specific location. The sign editor packet only uses that location. So, when the client receives the sign editor packet it just opens the editor and fills it's text with the block entity data it already has for that location.

As you can see in the provided video, if there is a sign at the location in the packet then the editor window stays open. At this time I am unsure if it's because the client actually validates the location for any sign block entity data, or if it's sending another request back to the server for updated block entity data. I'll leave that testing up to you.

[![Purpur #806 - Purpur #806 - Upstream (possibly vanilla) Issue](http://i3.ytimg.com/vi/Csm9JCiObEc/hqdefault.jpg)](https://youtu.be/Csm9JCiObEc)

**Comment by Lotzyprod** [comment]
Sorry for missing some points, but before open sign packet, I send block change
player.sendBlockChange(location,Material.OAK_WALL_SIGN,0), and this works on paper101, but doesn't work on purpur
https://youtu.be/0kvz9OW9JT0

**Comment by BillyGalbreath** [comment]
I just tried sending a fake block change first, and it seems to work fine.

https://youtu.be/fS3J2RI_xTE

```java
public final class TestPlugin extends JavaPlugin {
    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (!(sender instanceof Player player)) {
            sender.sendMessage("Player only command!");
            return true;
        }

        Location loc = player.getLocation();
        BlockPos pos = MCUtil.toBlockPosition(loc);

        // fake sign block
        player.sendBlockChange(loc, Material.OAK_SIGN.createBlockData());

        // populate sign text
        player.sendSignChange(loc, new String[]{"1", "2", "3", "4"});

        // open sign editor
        ((CraftPlayer) player).getHandle().connection.send(new ClientboundOpenSignEditorPacket(pos));

        return true;
    }
}
```
