### ISSUE TITLE
Iron Golem Farm not working

### ISSUE THREAD

**Issue by TheNerdAtWork** [pl3xgaming/Purpur#872]
### Timings link

[_Timings_](https://timings.aikar.co/?id=8b88f2ebe3f54befa124a4c5bcb87d37)

### Expected behavior

https://youtube.com/watch?v=JxPhPR9SNvY&feature=share

As shown in the video, everytime the villagers get scared by the zombie, an iron golem will spawn.

However, as soon as I converted my singleplayer world into a server. The farm broke.
Other farms seem to work(ianXO4's guardian XP farm)

### Observed/Actual behavior

Villagers are being scared but no Iron golem is spawning.

tried changing values of ;
 spawn-iron-golem:
          radius: 0
          limit: 0

But doesn't seem to do anything
//This issue was fixed by replacing beds.

Another issue occurred after this fix.

The Iron golem would then spawn on blocks it otherwise shouldn't be spawning on  (slabs, hoppers, stairs, chest, leaf blocks)
![image](https://user-images.githubusercontent.com/86414221/151390359-d6238c63-2375-4691-868b-ae4485bb5793.png)

### Steps/models to reproduce

https://youtube.com/watch?v=JxPhPR9SNvY&feature=share

You may follow the video and see if the farm works for you

### Purpur version

Current: git-Purpur-1533 (MC: 1.18.1)*
Previous: git-Purpur-1528 (MC: 1.18.1)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by BillyGalbreath** [comment]
Farms like that one do not work because Paper optimized block hitboxes/shapes. The villagers are constantly seeing the zombie, so they never get a chance to get unscared, which is an important requirement in iron farms. If they don't swap between being scared and not scared, they never really get a chance to sleep and reset internal timers for things like this.

Here is a farm I use that takes this into consideration and makes sure there is plenty of time for the villagers to be scared and not scared. It works like charm. https://www.youtube.com/watch?v=ZMD4KlXdkqs

**Comment by TheNerdAtWork** [comment]
So this is causing the iron golem to spawn outside the farm and on "unspawnable" blocks (slabs, stairs etc)?

**Comment by BillyGalbreath** [comment]
No, that issue is because you allowed iron golems to spawn in the air in paper.yml

`iron-golems-can-spawn-in-air: true`
