### ISSUE TITLE
Chunk not there when requested 

### ISSUE THREAD

**Issue by luizsusin** [pl3xgaming/Purpur#916]
### Expected behavior

Server not crashing.

### Observed/Actual behavior

Server crashes with IllegalStateException: Chunk not there when requested.

### Steps/models to reproduce

It happens randomly, not really something that is provoked. Sometimes it will pass a whole day without crashing, sometimes it just happens.

### Purpur version

Tested with git-Purpur-1559 (MC: 1.18.1), but I'm updating it to the latest version. However, I don't think there was major fixes on it.

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Crash Report: https://gist.github.com/luizsusin/faef3fd8361f6f8e918586987b7100b9

This might also be a problem with EcoEnchants, as it shows in the report. However, since I'm not really sure, I've opened this issue.
I can provide any information needed.
Thanks!

**Comment by BillyGalbreath** [comment]
Looks to be a bug with EcoEnchants trying to populate the loot of a lootable chest on chunk load.

**Comment by luizsusin** [comment]
> Looks to be a bug with EcoEnchants trying to populate the loot of a lootable chest on chunk load.

 EcoEnchants' LootPopulator is registered as a world populator, and thus not using any event (directly) to populate.
[EcoEnchantsPlugin.java at line 131](https://github.com/Auxilor/EcoEnchants/blob/a908723e8bada4edac9299307215b6a95a29cecb/eco-core/core-plugin/src/main/java/com/willfp/ecoenchants/EcoEnchantsPlugin.java#L131)

The [LootPopulator](https://github.com/Auxilor/EcoEnchants/blob/a908723e8bada4edac9299307215b6a95a29cecb/eco-core/core-plugin/src/main/java/com/willfp/ecoenchants/enchantments/support/obtaining/LootPopulator.java) itself doesn't seem to be problematic too. (I'm refering exclusively to _Chunk not there when requested_ exception)

It started happening on [Build 1548](https://github.com/PurpurMC/Purpur/commit/00ccf826434ffcbc942e7adcba6e103dee131b6a), which has updated the upstream with some world changes. Could it be related somehow?
I have the crash logs for that version too. I can attach them if needed.

**Comment by BillyGalbreath** [comment]
You're going to have to talk to the plugin author about this. It's a bug in their plugin.

Just examine your stacktrace, and you'll see it. Just remember to read it from bottom to top.

Line 37 the tick starts
Line 26 the chunk starts loading
Line 24-25 the plugin starts modifying the inventory of a lootable chest (inside a minecart to be exact)
Line 16 a random item is set to the inventory
Line 13 the server has to update all neighbors that the chest block changed (this is how things like observers and comparators work)
Line 12 is getting a neighbor block
Line 8-11 are getting the chunk this neighbor block belongs in
Line 7 is the error, telling you it can't get this chunk because it's in an unloaded ticket level (probably because it's in the same chunk as the chest being populated, which is in the middle of loading, but still not fully loaded).

The plugin is going to have to wait until the chunk is fully loaded before it can do any actions on it that call getChunk (see line 11).

**Comment by luizsusin** [comment]
That was a perfect elucidation, thank you so much for this. I'll get in touch with the developer.
