### ISSUE TITLE
Players teleporting 30m blocks with cheats

### ISSUE THREAD

**Issue by turret001** [pl3xgaming/Purpur#933]
### Timings link

none - check Other section

### Stack trace

```
https://paste.gg/p/anonymous/4d3fe1046a874127a6ccd9f4d07cfb55
```
I'm more than happy to provide a full console log in private. it contains IP addresses and in-game locations of the players and I wouldn't like to disclose that in public for the sake of privacy.

crash log: https://paste.gg/p/anonymous/943ea134533b40d2b5dbd7f694c92b57

### Actions to reproduce (if known)

Our guess is: someone's using viaforge and Future client (and rusher hack maybe), using packet flight or some other way to travel really fast. Server probably couldn't keep up with chunk generation and crashes.

### Purpur version

[11:09:44 INFO]: Checking version, please wait...
[11:09:44 INFO]: Current: git-Purpur-1596 (MC: 1.18.2)*
Previous: git-Purpur-1586 (MC: 1.18.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

So far we've gathered that people have been using Future Client with ViaForge and teleporting 30m blocks and causing server to crash with chunk generation load. 

I couldn't get a timings report because server kept crashing while I was away. People have been crashing the server to dupe their items (world doesn't get saved but their inventories does, or the other way around) and I didn't want them to do so. 

I'm on Purpur discord with turret001#0001 handle, feel free to DM me for the full log

**Comment by BillyGalbreath** [comment]
Closing due to not following template.

1) Timings link is NOT optional. It contains vital information for debugging issues like this. Even if.. no, Especially if you think it's not relevant.
2) You are NOT running the latest builds. 1586 is now a week old, and is 10 versions behind which includes some major updates from our upstreams.
3) This is a known issue that was discussed in Discord with the Vulcan plugin that was addressed weeks ago ([relevant Discord convo](https://discord.com/channels/685683385313919172/685683819608670209/948615958531043378)) but we can't tell if you have an older version of Vulcan or maybe the plugin just hasn't released an update with the information gained from the linked conversation.
4) You can use https://mclo.gs to post logs without worry of leaking private information such as player IPs. This paste service automagically redacts such information.

Since this is a known issue with Vulcan, I would suggest talking with their support to find a fix/workaround. There is nothing we can do on our end to fix this.
