### ISSUE TITLE
Cant put back pumpkin for snowman

### ISSUE THREAD

**Issue by KioProject123** [pl3xgaming/Purpur#942]
### Timings link

unnecessary

### Expected behavior

put back pumpkin for snowman

### Observed/Actual behavior

After deducting the pumpkin, the snowman has no pumpkin head

### Steps/models to reproduce

screenshot below

### Purpur version

screenshot below

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

### Other

Looks like the code is wrong

![image](https://user-images.githubusercontent.com/61594596/160346443-c31b12ad-5cd3-4b99-af21-8f255e22ab9b.png)

**Comment by BillyGalbreath** [comment]
Good catch. \o/ Looks like this has been an issue since June 2021 during a major overhaul.

https://github.com/PurpurMC/Purpur/commit/e4dd7cdae7a4ab0c89410de096357c87621a49d2#diff-0c6e7dd4c48bdde6aede0c15a694a7d644c04b20b9b224432e50c6cbd75030b9L17
https://github.com/PurpurMC/Purpur/commit/e4dd7cdae7a4ab0c89410de096357c87621a49d2#diff-5ceaf63e1dbabe0ba0c020116b276b2658ec09c1ae16bf4df88a01e08c17ab39R17
