### ISSUE TITLE
Feature Request: Config option for disabling sand dupe fix

### ISSUE THREAD

**Issue by Titaniumtown** [pl3xgaming/Purpur#98]
Could you add a config option to enable the vanilla sand dupe glitch? Similar to how TNT and carpet duping have config options.

Thanks!

**Comment by BillyGalbreath** [comment]
No.

**Comment by TetraTheta** [comment]
I don't know what exactly 'Sand Dupe' is, but Paper(Purpur is fork of that project) provides config for disabling dupe fix. [Here](https://paper.readthedocs.io/en/latest/server/configuration.html#unsupported-settings) but note that since it is under 'Unsupported Settings', you won't get any support from anyone from Paper or Purpur. Everyone would say 'Revert that setting to default' or 'You enabled unsupported setting, so we won't help you'. You will be entirely on your own.

**Comment by Titaniumtown** [comment]
@BillyGalbreath why not? I see no harm
