### ISSUE TITLE
Server crashes when trading with cartographer villager

### ISSUE THREAD

**Issue by Filosofas154** [pl3xgaming/Purpur#994]
### Timings link

https://timings.aikar.co/?id=843b09a2635e48b5b0f06ef14289df69

### Stack trace

https://paste.gg/p/anonymous/c792c8b69ba84716a2377c497f81f9f1/revisions

### Actions to reproduce (if known)

When the cartographer villager level-ups by trading the server crashes. 

### Purpur version

Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Purpur-1628 (MC: 1.18.2)
* You are running the latest version

### Agreements

- [X] I am running the latest version of Purpur available from https://purpurmc.org/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Purpur.

**Comment by Minoo1233** [comment]
same problem, purpur 1.18.2

**Comment by BillyGalbreath** [comment]
This is caused by the cartographer searching for monuments to put on maps. This is a vanilla issue and nothing we can really do to fix it.

Check these bug reports for more information.

https://github.com/PaperMC/Paper/issues/7664
https://github.com/PaperMC/Paper/issues/7269
https://github.com/PaperMC/Paper/issues/2312
